# Generated by Django 6.0.4 on 2026-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('winning_candidate_2021', models.CharField(max_length=150)),
                ('winning_party_2021', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
    ]
