# Generated by Django 6.0.4 on 2026-05-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='live_leading_party',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='live_margin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constituency',
            name='live_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
